let member = {
    "ami":{
        color:"linear-gradient(90deg, #13bee9, #4bbe95)",
        color2:"#4bbe95",
        name:"あみ",
        title:"不老不死になりたい",
        discription:"マイクラでは山を消し、スプラでは塗り絵をする女の子。<br>単純作業が好きで何時間でも続けている。<br>ふらんに出会うまでマイクラのビーコンを知らなかった。",
        height: "157cm",
        birthday: "6/13",
        twitter:"",
        tag:"Splatoon3,MINECRAFT,マイクラ人狼,TRPG,麻雀",
        tagcolor:"white"
    },
    "ane":{
        color:"#b28194",
        name:"姉ちゃん",
        title:"Hakumai is my life.",
        discription:'可愛い女の子とアイドルが好きなゲラおじさん。<br>メンマは割り箸だと教えられてガチで信じたことがある。<br>ちなみにいもうとのガチ姉。',
        height: "153cm",
        birthday: "9/12",
        twitter:"https://twitter.com/neeechaaanda",
        tag:"APEX,Splatoon3,ポケモン,マリオカート,MINECRAFT,マイクラ人狼,麻雀",
        tagcolor:"white"
    },
    "chiwa":{
        color:"#cc4474",
        name:"ちわ小太郎",
        title:"ちゃうんすよ",
        discription:"zippoで焦がした前髪は数知れず。<br>髪色髪型がコロコロ変わる。<br>日課は筋トレとランニング。",
        height: "167cm",
        birthday: "12/20",
        twitter:"https://twitter.com/chiwa69853238",
        tag:"APEX,Splatoon3,ポケモン,遊戯王,MINECRAFT,マイクラ人狼,麻雀,ヤニカス",
        tagcolor:"white"
    }, 
    "cta":{
        color:"#29f6fb",
        name:"C太",
        title:"だめだよーん",
        discription:"",
        height: "",
        birthday: "",
        twitter:"https://twitter.com/c_ta_oekaki",
        tag:"APEX,Splatoon3,MINECRAFT,マイクラ人狼,麻雀",
        tagcolor:"black"
    }, 
    "fran":{
        color:"#a9fc18",
        name:"Frandle256",
        title:"きゅんです",
        discription:"吸血鬼。<br>飲んでるのは血かと思いきやトマトジュース。<br>自称みんなのアイドル。かわいくなりたい。",
        height: "161cm",
        birthday: "5/3",
        twitter:"https://twitter.com/Frandle_256",
        tag:"APEX,Splatoon3,マリオカート,R6S,MINECRAFT,マイクラ人狼,TRPG,麻雀,VALORANT",
        tagcolor:"black"
    }, 
    "gale":{
        color:"#82c6b7",
        name:"gale",
        title:"",
        discription:"",
        height: "",
        birthday: "",
        twitter:"https://twitter.com/gale43hs",
        tag:"Splatoon3,ポケモン,遊戯王",
        tagcolor:"white"
    }, 
    "han":{
        color:"linear-gradient(90deg,#a599a5 ,#d1ccb6)",
        color2:"#d1ccb6",
        name:"3010",
        title:"Trap & Trick",
        discription:"罠をこよなく愛する武器商人。<br>他人の足元を掬う事に生き甲斐を感じている。性格が悪く笑い方が悪役。<br>実はカラコンをつけており本来は両方黒目、タトゥーもシールである。",
        height: "156cm",
        birthday: "8/17",
        twitter:"https://twitter.com/hanteeeeeeen",
        tag:"APEX,Splatoon3,ポケモン,マリオカート,遊戯王,R6S,MINECRAFT,マイクラ人狼,麻雀,VALORANT,ヤニカス",
        tagcolor:"black"
    }, 
    "imo":{
        color:"#7a5f72",
        name:"いもうと",
        title:"真ハン足元",
        discription:"元人間の悪魔でBOSG愛好家。<br>TRPGとFPSを反復横跳びしている。<br>ちなみに姉ちゃんのガチ妹。",
        height: "146cm",
        birthday: "2/10",
        twitter:"https://twitter.com/imoutodesudesu",
        tag:"APEX,R6S,TRPG,麻雀,OW2",
        tagcolor:"white"
    }, 
    "kyomu":{
        color:"#890000",
        name:"虚無虚無ぷりん",
        title:"溢れたミルクは返らない",
        discription:"雌型の姿。本来は深淵から這い出るナニカ。<br>創造する力は現在、イラストと製菓にしか生かされていない。<br>雄型はバイト戦士。",
        height: "156㎝ or 170㎝",
        birthday: "8/29",
        twitter:"",
        tag:"APEX,ポケモン,R6S,MINECRAFT,マイクラ人狼,TRPG,麻雀",
        tagcolor:"white"
    }, 
    "mike":{
        color:"#e58d1f",
        name:"若草みけ",
        title:"和を以て貴しとなす",
        discription:"大企業グループ傘下の警備会社に勤める一般人。<br>めっちゃ運が悪い。直近では人工肉培養プラントの警備に従事している。<br>好きなものは飯と睡眠、そしてゲーム。",
        height: "180cm",
        birthday: "10/24",
        twitter:"https://twitter.com/mikei_222",
        tag:"APEX,Splatoon3,ポケモン,マリオカート,遊戯王,R6S,MINECRAFT,マイクラ人狼,TRPG,麻雀,VALORANT",
        tagcolor:"white"
    }, 
    "retoro":{
        color:"#555555",
        name:"れとろ",
        title:"ちいこきｲﾉﾁは健康にいい",
        discription:'貝殻と生き物全般が好きな性別不詳ﾂｰﾄﾝ伏し目。<br>抱えてる黒いおはぎの方が本来の姿。<br>定期的にちいこきｲﾉﾁを爆誕させる。',
        height: "10～192cm",
        birthday: "2/4",
        twitter:"https://twitter.com/0490sgr",
        tag:"APEX,Splatoon3,R6S,MINECRAFT,マイクラ人狼,麻雀",
        tagcolor:"white"
    }, 
    "sayu":{
        color:"#aaeddb",
        name:"白湯丸太",
        title:"は？(威圧)",
        discription:"",
        height: "",
        birthday: "",
        twitter:"https://twitter.com/sayu_kikaku",
        tag:"麻雀",
        tagcolor:"black"
    }, 
    "shigure":{
        color:"#fb0304",
        name:"ふみしぐれ",
        title:"犯人はお前だーーーッ！！(誤)",
        discription:"運とパッションで強引に事件を解決させるエンターテイナー名探偵。<br>自称名探テイナー。<br>斧を持ち歩いてる不審者。",
        height: "166cm",
        birthday: "2/27",
        twitter:"https://twitter.com/shigure_DbD",
        tag:"APEX,Splatoon3,ポケモン,マリオカート,遊戯王,R6S,MINECRAFT,マイクラ人狼,TRPG,麻雀,VALORANT",
        tagcolor:"white"
    }, 
    "takei":{
        color:"#89ead7",
        name:"夕ケイ",
        title:"ｳﾞｰｰｰｰｰｰｰｰｰｰｰｰｰｯ!!!!!!!!!!!!(威嚇)",
        discription:'猫耳ヘアとスプタンがアイデンティティのMtF。<br>3日でヤニに落ちたヤニカス。<br>舌の魔改造とタバコと激辛好きのせいで舌がんのリスクがピカイチ。',
        height: "180cm",
        birthday: "11/21",
        twitter:"https://twitter.com/_125tKtt",
        tag:"Splatoon3,ポケモン,MINECRAFT,マイクラ人狼,TRPG,麻雀,ヤニカス",
        tagcolor:"black"
    }, 
    "via":{
        color:"#728474",
        name:"VIA",
        title:"",
        discription:"",
        height: "",
        birthday: "",
        twitter:"https://twitter.com/KimagureViasan",
        tag:"ヤニカス",
        tagcolor:"white"
    }, 
    "yoro":{
        color:"#3a685e",
        name:"吉岡よろ",
        title:"郷に入っては郷に従え",
        discription:"糸目エセ関西弁の妖怪。<br>アユの塩焼きが好き。<br>ゲームは大体酔うと思え。",
        height: "155cm",
        birthday: "5/8",
        twitter:"https://twitter.com/kikakuyoshi",
        tag:"APEX,Splatoon3,ポケモン,マリオカート,MINECRAFT,マイクラ人狼,麻雀",
        tagcolor:"white"
    }, 
    "yupi":{
        color:"#0060ff",
        name:"木林ユピテル",
        title:"では戦闘ということでよろしいか",
        discription:'日々「究極の一撃」を求めて様々な兵器の開発に勤しむ研究者。<br>実戦運用とかコストとかそんなのは気にしない。<br>好きな物は酒とエナドリとタバコ',
        height: "150cm",
        birthday: "3/17",
        twitter:"https://twitter.com/6m10cm",
        tag:"APEX,Splatoon3,ポケモン,遊戯王,R6S,MINECRAFT,マイクラ人狼,TRPG,麻雀,VALORANT,ヤニカス",
        tagcolor:"white"
    },
    "zen":{
        color:"#c11dff",
        name:"漸化式",
        title:"cute aggression",
        discription:"社畜の化身。残業？いやいや自己研鑽。<br>単純な顔した小さいものがだぁいすき。<br>でも近寄るな、殴るぞ。",
        height: "175cm",
        birthday: "3/20",
        twitter:"https://twitter.com/marty99_zen",
        tag:"APEX,Splatoon3,ポケモン,マリオカート,遊戯王,MINECRAFT,マイクラ人狼,TRPG,麻雀,ヤニカス",
        tagcolor:"white"
    }
  }